sudo: false

language: c

compiler:
 - clang
 - gcc

install:
  - if [ "$CC" = "gcc" ]; then export CFLAGS="-std=c11"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
  - if [ "$CC" = "clang" ]; then export CFLAGS="-std=c11"; fi
  - if [ "$CC" = "clang" ]; then export CC="clang-3.7"; fi

script:
 - make --directory=compiler CC="${CC}" CFLAGS="${CFLAGS}"

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-3.7
   - llvm-toolchain-precise
  packages:
   - make
   - clang-3.7
   - gcc-5
