# -*- coding: utf-8 -*-
#
# mana (compiler/library)
#
# @brief	Script file for version information
# @detail	This file is a script file for version information.
# @author	Shun Moriya
# @date		2017-
#

import datetime
import json
from pathlib import Path

directory = Path(__file__).resolve().parent
version = json.loads((directory / 'Version.json').read_text(encoding='utf-8'))
for key in ('MajorVersion', 'MinorVersion', 'PatchVersion'):
    if type(version[key]) is not int or version[key] < 0:
        raise ValueError(f'{key} must be a non-negative integer')

number = f'{version["MajorVersion"]}.{version["MinorVersion"]}.{version["PatchVersion"]}'
now = datetime.datetime.now()

(directory / 'Version.h').write_text('''/*!
 * mana (compiler/library)
 * 
 * @file   Version.h
 * @brief  Script file for version information
 * @detail This file is a script file for version information.
 *         that it is automatically generated by Version.py
 * @author Shun Moriya
 * @date   2003-
 */

#pragma once

namespace mana::version
{{
    inline constexpr int MajorVersion = {major};
    inline constexpr int MinorVersion = {minor};
    inline constexpr int PatchVersion = {patch};
    inline constexpr char Number[] = {number};
    inline constexpr int Year = {year};
    inline constexpr int Month = {month};
    inline constexpr int Day = {day};
    inline constexpr int Hour = {hour};
    inline constexpr int Minute = {minute};
}}
'''.format(major=version['MajorVersion'], minor=version['MinorVersion'],
           patch=version['PatchVersion'], number=json.dumps(number),
           year=now.year, month=now.month,
           day=now.day, hour=now.hour, minute=now.minute), encoding='utf-8')
