/*!
mana (compiler)

@file	Compiler.cpp
@brief	コンパイラの組み込み用インターフェース
@detail	このファイルはコンパイラをライブラリとして利用する為のソースファイルです。
@author	Shun Moriya
@date	2026-
*/

#include "../runner/common/Setup.h"
#include "Compiler.h"
#include "CodeGenerator.h"
#include "DataBuffer.h"
#include "ErrorHandler.h"
#include "Lexer.h"
#include "ParsingDriver.h"
#include "Path.h"
#include "SymbolFactory.h"
#include "SyntaxNode.h"

#include <cstring>
#include <ctime>
#include <exception>
#include <limits>
#include <new>
#include <sstream>

namespace mana
{
	namespace
	{
		/*!
		作業ディレクトリを退避し、スコープを抜ける時に復帰します

		字句解析器はインクルードを解決する為に作業ディレクトリを変更します。
		ライブラリとして組み込まれた場合、その変更が呼び出し元へ漏れると
		予期しない不具合を招くため必ず復帰させます。
		*/
		class ScopedWorkingDirectory final
		{
		public:
			ScopedWorkingDirectory()
				: mPath(getcurrentdirectory())
			{
			}

			~ScopedWorkingDirectory()
			{
				if (!mPath.empty())
				{
					chdir(mPath.c_str());
				}
			}

			ScopedWorkingDirectory(const ScopedWorkingDirectory& other) = delete;
			ScopedWorkingDirectory(ScopedWorkingDirectory&& other) noexcept = delete;
			ScopedWorkingDirectory& operator=(const ScopedWorkingDirectory& other) = delete;
			ScopedWorkingDirectory& operator=(ScopedWorkingDirectory&& other) noexcept = delete;

		private:
			std::string mPath;
		};

		/*!
		字句解析器を確実に終了させます
		*/
		class ScopedLexer final
		{
		public:
			ScopedLexer() = default;

			~ScopedLexer()
			{
				lexer::Finalize();
			}

			ScopedLexer(const ScopedLexer& other) = delete;
			ScopedLexer(ScopedLexer&& other) noexcept = delete;
			ScopedLexer& operator=(const ScopedLexer& other) = delete;
			ScopedLexer& operator=(ScopedLexer&& other) noexcept = delete;
		};

		/*!
		シンボル表・構文木・中間コードをマークダウンへ出力します
		*/
		[[nodiscard]] std::string GenerateDump(const std::shared_ptr<ParsingDriver>& parser)
		{
			std::ostringstream output;

			if (parser->GetSymbolFactory())
			{
				output << "# Symbol Table\n";
				parser->GetSymbolFactory()->Dump(output);
				output << "\n";
			}
			if (parser->GetRootSyntaxNode())
			{
				output << "# Syntax Node\n";
				parser->GetRootSyntaxNode()->Dump(output);
			}
			if (parser->GetCodeGenerator())
			{
				output << "# Code\n";
				output << "```\n";
				parser->GetCodeGenerator()->Dump(output);
				output << "```\n";
			}

			return output.str();
		}

		/*!
		C++の型宣言ヘッダーを出力します
		*/
		[[nodiscard]] std::string GeneratePublicTypeDecl(const std::shared_ptr<ParsingDriver>& parser, const std::string& sourceFilename)
		{
			std::ostringstream output;

			output << "/*\n";
			output << " * This file was automatically generated based on '" << sourceFilename << "'.\n";
			output << " * Do not edit this file, as any changes will be overwritten.\n";
			output << " */\n";
			output << "#pragma once\n";
			output << "#include <cstdint>\n\n";
			output << "namespace mana\n{\n";
			parser->GetSymbolFactory()->WritePublicTypeDecl(output);
			output << "}\n";

			return output.str();
		}

		/*!
		プログラムイメージを生成します
		*/
		[[nodiscard]] bool GenerateProgramImage(OutputStream& stream, const std::shared_ptr<ParsingDriver>& parser)
		{
			FileHeader header = {};
			memcpy(&header.mHeader, Signature, sizeof(header.mHeader));
			header.mMajorVersion = MajorVersion;
			header.mMinorVersion = MinorVersion;

			if (IsBigEndian())
				header.mFlag |= (1 << FileHeader::Flag::BigEndian);
#if UINTPTR_MAX == UINT64_MAX
			header.mFlag |= (1 << FileHeader::Flag::Is64Bit);
#endif
			const size_t numberOfActors = parser->GetSymbolFactory()->GetNumberOfActors();
			if (std::numeric_limits<uint32_t>::max() < numberOfActors)
				throw std::overflow_error("Too many actors defined");
			header.mNumberOfActors = static_cast<uint32_t>(numberOfActors);
			header.mSizeOfConstantPool = parser->GetDataBuffer()->GetSize();
			header.mSizeOfInstructionPool = parser->GetCodeBuffer()->GetSize();
			header.mSizeOfStaticMemory = parser->GetSymbolFactory()->GetStaticMemoryAddress();
			header.mSizeOfGlobalMemory = parser->GetSymbolFactory()->GetGlobalMemoryAddress();
			header.mRandomSeedNumber = static_cast<uint32_t>(time(nullptr));

			stream.PushData(&header, sizeof(header));

			if (!parser->GetSymbolFactory()->GenerateActorInformation(stream))
			{
				return false;
			}

			parser->GetDataBuffer()->Write(stream);
			parser->GetCodeBuffer()->Write(stream);

			return true;
		}

		/*!
		コンパイルの本体

		診断は呼び出し元が用意した DiagnosticBag へ集約されるため、
		この関数は成否を返しません。
		*/
		void CompileCore(const CompileOptions& options, CompileResult& result)
		{
			auto parser = std::make_shared<ParsingDriver>();
			if (parser == nullptr)
				throw std::bad_alloc();

			ScopedLexer scopedLexer;

			if (!lexer::Initialize(parser, options.mSourceFilename))
				return;

			// 先に指定されたファイルほど先に読み込まれるよう逆順に積みます
			for (auto it = options.mForcedIncludeFiles.rbegin(); it != options.mForcedIncludeFiles.rend(); ++it)
			{
				if (!lexer::Open(*it, false))
				{
					// 入れ子のファイルを開けなかった場合、字句解析器は診断を報告しません
					LinkerError({ "unable to open forced include file \"", *it, "\"" });
					return;
				}
			}

			const bool parsed = (parser->Parse() == 0) && (yynerrs == 0);

			if (parsed && options.mGeneratePublicTypeDecl)
			{
				result.mPublicTypeDecl = GeneratePublicTypeDecl(parser, options.mSourceFilename);
			}

			if (options.mGenerateDump)
			{
				result.mDump = GenerateDump(parser);
			}

			parser->GetSymbolFactory()->CheckUndefine();

			if (!parsed)
				return;

			OutputStream stream;
			if (!GenerateProgramImage(stream, parser))
				return;

			const uint8_t* buffer = static_cast<const uint8_t*>(stream.GetBuffer());
			const size_t size = stream.GetUsedSize();
			if (buffer != nullptr && size > 0)
			{
				result.mProgramImage.assign(buffer, buffer + size);
			}
		}
	}

	CompileResult Compile(const CompileOptions& options)
	{
		CompileResult result;

		// 字句解析器が変更する作業ディレクトリを呼び出し元へ漏らしません
		const ScopedWorkingDirectory scopedWorkingDirectory;

		DiagnosticBag bag(options.mSourceFilename, options.mDiagnosticHandler);

		// 繰り返し呼び出せるようグローバルなエラー数を初期化します
		yynerrs = 0;

		try
		{
			CompileCore(options, result);
		}
		catch (const std::exception& e)
		{
			Fatal(e.what());
		}
		catch (...)
		{
			Fatal("unknown exception");
		}

		result.mSucceeded = (bag.GetErrorCount() == 0);
		if (!result.mSucceeded)
		{
			result.mProgramImage.clear();
			result.mPublicTypeDecl.clear();
		}
		result.mDiagnostics = bag.Release();

		return result;
	}
}
