/*!
mana (compiler)

@file	Version.h
@brief	Script file for version information
@detail	This file is a script file for version information.
		Note that it is automatically generated by Version.py
@author	Shun Moriya
@date	2003-
*/

#pragma once
#include <cstdint>
namespace mana
{
	namespace build
	{
		static constexpr int32_t Year = 2022;
		static constexpr int32_t Month = 9;
		static constexpr int32_t Day = 18;
		static constexpr int32_t Hour = 23;
		static constexpr int32_t Minute = 19;
		static const char* MajorVersion = "0";
		static const char* MinorVersion = "9.7";
	}
}