/*!
mana (compiler)

@file	Version.h
@brief	Script file for version information
@detail	This file is a script file for version information.
		Note that it is automatically generated by Version.py
@author	Shun Moriya
@date	2003-
*/

#pragma once
#include <cstdint>
namespace mana
{
	namespace build
	{
		static constexpr int32_t Year = 2022;
		static constexpr int32_t Month = 10;
		static constexpr int32_t Day = 7;
		static constexpr int32_t Hour = 21;
		static constexpr int32_t Minute = 20;
		static const char* MajorVersion = "0";
		static const char* MinorVersion = "9.7";
	}
}